---
abstract: 'Try to explain what $ @ % & * and the rest mean'
author:
  - 'Gabor Szabo'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Deep: 0.01
  Test::More: 0.88
  Test::NoWarnings: 0.084
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Code-Explain
no_index:
  directory:
    - inc
    - t
requires:
  PPI: 1.213
  Pod::Usage: 0
  perl: 5.008008
resources:
  homepage: http://code.szabgab.com/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/szabgab/Code-Explain
version: 0.02
